# Generated by Django 5.1.6 on 2025-02-27 11:33

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration script performs the following operations:

    1. Inserts a new record into the `store_collection` table with the title 'Summer collection'.
    2. Provides a reverse operation to delete the record from the `store_collection` table where the title is 'Summer collection'.

    Dependencies:
    - Depends on the migration '0003_add_slug_to_product' in the 'store' app.

    Operations:
    - RunSQL: Executes raw SQL to insert and delete the 'Summer collection' record in the `store_collection` table.

    """

    dependencies = [
        ("store", "0003_add_slug_to_product"),
    ]

    operations = [
        migrations.RunSQL(
            """
                          INSERT INTO store_collection (title)
                          VALUES ('Summer collection');
                          """,
            """
                          DELETE FROM store_collection
                          WHERE title = 'Summer collection';
                          """,
        )
    ]
